-- MySQL Script generated by MySQL Workbench
-- Tue Oct  6 01:00:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema zello
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zello` ;

-- -----------------------------------------------------
-- Schema zello
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zello` DEFAULT CHARACTER SET latin1 ;
USE `zello` ;

-- -----------------------------------------------------
-- Table `zello`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zello`.`perfil` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `zello`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zello`.`pessoa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(255) NULL DEFAULT NULL,
  `dt_nascimento` DATETIME(6) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `rg` VARCHAR(255) NULL DEFAULT NULL,
  `perfil_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKb6hmq74hc2bxk1y9inb26o7au` (`perfil_id` ASC),
  CONSTRAINT `FKb6hmq74hc2bxk1y9inb26o7au`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `zello`.`perfil` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `zello`.`perfil` (`nome`) VALUES ('comum');
INSERT INTO `zello`.`perfil` (`nome`) VALUES ('gestor');
INSERT INTO `zello`.`perfil` (`nome`) VALUES ('admin');